"""users email + avatar_history

Revision ID: a0153a6f63a7
Revises: 0d03d3bdaaf4
Create Date: 2026-08-13 02:25:09.771272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0153a6f63a7'
down_revision: Union[str, Sequence[str], None] = '0d03d3bdaaf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(), server_default='', nullable=False))
    op.add_column('users', sa.Column('avatar_history', sa.String(), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_history')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
