"""email_codes resent_at

Revision ID: c8784f3ca65c
Revises: dfdf2111a499
Create Date: 2026-08-13 05:15:42.184876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8784f3ca65c'
down_revision: Union[str, Sequence[str], None] = 'dfdf2111a499'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_codes', sa.Column('resent_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_codes', 'resent_at')
    # ### end Alembic commands ###
